-- ============================================================================
-- 44 — ⛔ OBSOLETO / NO EJECUTAR ⛔  (reemplazado por el rollback 45)
-- ----------------------------------------------------------------------------
-- Este script fue un ERROR de diagnóstico. La supuesta diferencia libro-vs-físico
-- NO era producción fantasma: eran transacciones con status='rechazado' que el
-- cálculo de conciliación contaba mal. El físico (saldoinvdetalle) SIEMPRE estuvo
-- correcto — los meses sí cuadraban.
--
-- Además, existe un trigger invtrans -> saldoinvdetalle que aplicó estos ajustes
-- y contaminó el físico con filas fantasma en la ubicación 'AJUSTE-SIG'.
--
-- ACCIÓN CORRECTA:
--   1) Ejecutar  45_rollback_ajuste_conciliacion.sql  (limpia lo que hizo el 44).
--   2) La conciliación ya se corrigió EN EL CÓDIGO (lib/sig-actions.ts): ahora
--      excluye las transacciones 'rechazado'. No se toca la fuente de datos.
--
-- Se deja el archivo como registro de auditoría. NO EJECUTAR.
-- ============================================================================
