-- ============================================================================
-- RLS para `bonos_nomina` — cierra el bypass de la clave de aprobación
-- ----------------------------------------------------------------------------
-- POR QUÉ:
-- Aprobar un bono exige clave, y esa clave se valida en el SERVIDOR
-- (lib/bonos-actions.ts, `"use server"` — nunca viaja al navegador). Eso protege
-- contra quien use la aplicación.
--
-- Pero la tabla NO tiene RLS, y la anon key de Supabase es PÚBLICA por diseño
-- (viaja en el bundle como NEXT_PUBLIC_SUPABASE_ANON_KEY). Comprobado el
-- 31-jul-2026 sobre la base real: desde la consola del navegador,
--
--     supabase.from('bonos_nomina').update({estado:'aprobado'}).eq('id', N)
--
-- aprueba el bono SIN clave, saltándose por completo la server action. Ese bono
-- aprobado entra a `pagonomina.bonif_no_prestacional` y sale en el archivo plano
-- con su novedad — es decir, se paga.
--
-- QUÉ HACE ESTE SCRIPT:
-- Activa RLS y NO crea ninguna política. Sin políticas, `anon` y `authenticated`
-- quedan sin acceso; el `service_role` (el que usa `getSupabaseAdmin`) salta RLS
-- por definición, así que la app sigue funcionando igual.
--
-- POR QUÉ ES SEGURO AQUÍ:
--   · `bonos_nomina` solo se toca desde lib/bonos-actions.ts, y ese archivo usa
--     SIEMPRE `getSupabaseAdmin()` (service_role). Ningún componente la lee con
--     el cliente del navegador — verificado por búsqueda en todo el repo.
--   · Las vistas `pagonomina` y `archivoplano` la leen, pero una vista en
--     Postgres corre con los permisos de SU DUEÑO salvo que se marque
--     `security_invoker = true`. Estas no lo están, así que siguen leyendo la
--     tabla sin tropezar con RLS.
--
-- OJO — ALCANCE: esto arregla SOLO `bonos_nomina`. La falta de RLS es la postura
-- de toda la base (headcount, cabeceraoc, registroasistencia y
-- permisos_usuarios también aceptan lectura con la anon key). Cerrarlo completo
-- es un trabajo aparte y una decisión de negocio, no algo que deba salir de
-- este módulo.
--
-- REVERSIBLE:  ALTER TABLE public.bonos_nomina DISABLE ROW LEVEL SECURITY;
-- ============================================================================

ALTER TABLE public.bonos_nomina ENABLE ROW LEVEL SECURITY;

-- Verificación (debe devolver rowsecurity = true):
--   SELECT relname, relrowsecurity FROM pg_class WHERE relname = 'bonos_nomina';
--
-- Y después, desde la app: registrar un bono, aprobarlo con la clave y ver que
-- siga apareciendo en Revisión de nómina y en el archivo plano.
